services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - auth