http:
  routers:
    health-route:
      rule: "Path(`/health`)"
      service: "auth-service"
      entryPoints:
        - "web"
      priority: 100
      ruleSyntax: "v3"

    auth-route:
      rule: "Path(`/auth`)"
      service: "auth-service"
      entryPoints:
        - "web"
      priority: 90
      ruleSyntax: "v3"

    root-route:
      rule: "Path(`/`)"
      service: "auth-service"
      middlewares:
        - "auth-forward"
      entryPoints:
        - "web"
      priority: 1
      ruleSyntax: "v3"

  middlewares:
    auth-forward:
      forwardAuth:
        address: "http://submission_auth:5000/auth"
        trustForwardHeader: true
        authRequestHeaders:
          - "x-pretest"

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://submission_auth:5000"